name: skaffold-kaniko
label: Skaffold Kaniko example
markdownDescription: |2
  This is an [example](https://github.com/GoogleContainerTools/skaffold/tree/master/examples/kaniko) demonstrating
  * *building* a single go file app and with a single stage `Dockerfile` using [kaniko](https://github.com/GoogleContainerTools/kaniko) to build on a K8S cluster
  * *tagging* using the default tagPolicy (`gitCommit`)
  * *deploying* a single container pod using `kubectl`
insertText: |2
  apiVersion: skaffold/v1beta2
  kind: Config
  build:
    artifacts:
    - image: ${1:gcr.io/k8s-skaffold/skaffold-example}
    kaniko:
      buildContext: 
        gcsBucket: ${2:bucket-name}
      pullSecretName: ${3:secret-name}
      namespace: default
      cache: {}
  deploy:
    kubectl:
      manifests:
        - k8s-*