name: skaffold-helm-deployment
label: Skaffold Helm deployment example
markdownDescription: |2
  **Deploy multiple releases with Helm**

  You can deploy multiple releases with skaffold, each will need a chartPath, a values file, and namespace.
  Skaffold can inject intermediate build tags in the the values map in the skaffold.yaml. [Read more.](https://github.com/GoogleContainerTools/skaffold/tree/master/examples/helm-deployment)
  [Read more.](https://github.com/GoogleContainerTools/skaffold/tree/master/examples/helm-deployment)
insertText: |2
  apiVersion: skaffold/v1beta2
  kind: Config
  build:
    tagPolicy:
      sha256: {}
    artifacts:
    - image: ${1:gcr.io/k8s-skaffold/skaffold-helm}
  deploy:
    helm:
      releases:
      - name: skaffold-helm
        chartPath: skaffold-helm
        #wait: true
        #valuesFiles:
        #- helm-skaffold-values.yaml
        values:
          image: ${1:gcr.io/k8s-skaffold/skaffold-helm}
        #recreatePods will pass --recreate-pods to helm upgrade
        #recreatePods: true
        #overrides builds an override values.yaml file to run with the helm deploy
        #overrides:
        # some:
        #   key: someValue
        #setValues get appended to the helm deploy with --set.  
        #setValues:
          #some.key: someValue