name: skaffold-getting-started
label: Skaffold getting-started example
markdownDescription: |2
  This is a simple [example](https://github.com/GoogleContainerTools/skaffold/tree/master/examples/getting-started) based on

  * *building* a single go file app and with a multistage `Dockerfile` using local docker to build
  * *tagging* using the default tagPolicy (`gitCommit`)
  * *deploying* a single container pod using `kubectl`
insertText: |2
  apiVersion: skaffold/v1beta2
  kind: Config
  build:
    artifacts:
    - image: ${1:gcr.io/k8s-skaffold/skaffold-example}
  deploy:
    kubectl:
      manifests:
        - k8s-*